name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform to build for (all, android, website)"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - android
          - website

concurrency:
  group: "build-and-deploy"
  cancel-in-progress: true

jobs:
  # Website deployment
  deploy-website:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.inputs.platform == 'website' || github.event.inputs.platform == 'all'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install website dependencies
        run: |
          cd website
          npm ci

      - name: Build website
        run: |
          cd website
          npm run build
        env:
          REACT_APP_GITHUB_REPO: ${{ github.repository }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./website/build"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Android build
  build-android:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo CLI
        run: npm install -g @expo/cli eas-cli

      - name: Setup EAS Authentication
        run: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "Error: EXPO_TOKEN is not set or is empty"
            exit 1
          fi
          echo "EXPO_TOKEN is set and ready for EAS authentication"
          # EAS CLI will automatically use EXPO_TOKEN environment variable
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Check for recent builds
        id: check-builds
        run: |
          # Check if there's a recent successful build (within last 2 hours)
          echo "Checking for recent builds..."
          
          # Get build list and handle potential errors
          BUILD_LIST=$(eas build:list --platform android --status finished --limit 1 --json 2>/dev/null || echo "[]")
          
          if [ "$BUILD_LIST" = "[]" ] || [ -z "$BUILD_LIST" ]; then
            echo "No builds found, will create new build"
            echo "skip_build=false" >> $GITHUB_OUTPUT
          else
            # Try to extract build ID and creation time
            BUILD_ID=$(echo "$BUILD_LIST" | jq -r '.[0].id // empty' 2>/dev/null || echo "")
            CREATED_AT=$(echo "$BUILD_LIST" | jq -r '.[0].createdAt // empty' 2>/dev/null || echo "")
            
            if [ -n "$BUILD_ID" ] && [ -n "$CREATED_AT" ]; then
              echo "Found build: $BUILD_ID created at $CREATED_AT"
              echo "Using existing build"
              echo "skip_build=true" >> $GITHUB_OUTPUT
              echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
            else
              echo "Could not parse build information, will create new build"
              echo "skip_build=false" >> $GITHUB_OUTPUT
            fi
          fi
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android APK
        if: steps.check-builds.outputs.skip_build != 'true'
        run: |
          # Run the cloud build without --output
          eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          REACT_APP_GITHUB_REPO: ${{ github.repository }}

      - name: Get Build Download Link
        id: get-build-link
        run: |
          # Get the latest build and extract download link
          echo "Getting latest build download link..."
          BUILD_LIST=$(eas build:list --platform android --status finished --limit 1 --json 2>/dev/null || echo "[]")
          
          if [ "$BUILD_LIST" = "[]" ] || [ -z "$BUILD_LIST" ]; then
            echo "Error: No builds found"
            exit 1
          fi
          
          BUILD_ID=$(echo "$BUILD_LIST" | jq -r '.[0].id // empty' 2>/dev/null || echo "")
          DOWNLOAD_URL=$(echo "$BUILD_LIST" | jq -r '.[0].artifacts.buildUrl // empty' 2>/dev/null || echo "")
          
          if [ -z "$BUILD_ID" ]; then
            echo "Error: Could not extract build ID"
            exit 1
          fi
          
          if [ -z "$DOWNLOAD_URL" ]; then
            echo "Error: Could not extract download URL"
            exit 1
          fi
          
          echo "Build ID: $BUILD_ID"
          echo "Download URL: $DOWNLOAD_URL"
          echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
          echo "download_url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Create Build Info File
        run: |
          # Create a JSON file with build information for the website
          cat > build-info.json << EOF
          {
            "buildId": "${{ steps.get-build-link.outputs.build_id }}",
            "downloadUrl": "${{ steps.get-build-link.outputs.download_url }}",
            "buildDate": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "version": "${{ github.run_number }}"
          }
          EOF
          echo "Created build-info.json:"
          cat build-info.json

      - name: Upload Build Info
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: build-info.json
          if-no-files-found: error

      - name: Copy Build Info to Website
        run: |
          # Copy build info to website public folder for access
          cp build-info.json website/public/
          echo "Copied build-info.json to website/public/"

  # Create release with build info
  create-release:
    needs: [build-android]
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' &&
      needs.build-android.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Info
        uses: actions/download-artifact@v4
        with:
          name: build-info
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            ## ThePirithApp Release v${{ github.run_number }}

            ### What's New
            - Latest updates and bug fixes

            ### Downloads
            - **Android APK**: [Download from EAS](https://expo.dev/artifacts/eas/${{ needs.build-android.outputs.build_id }}.apk)

            ### Installation Instructions
            - **Android**: Download APK and enable "Install from unknown sources"

            Built automatically from commit: ${{ github.sha }}
            
            ### Build Information
            - Build ID: ${{ needs.build-android.outputs.build_id }}
            - Build Date: ${{ needs.build-android.outputs.build_date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
