name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: "build-deploy"
  cancel-in-progress: true

jobs:
  # Website deployment
  deploy-website:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install website dependencies
        run: |
          cd website
          npm ci

      - name: Build website
        run: |
          cd website
          npm run build
        env:
          REACT_APP_GITHUB_REPO: ${{ github.repository }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./website/build"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Android build
  build-android:
    runs-on: ubuntu-latest
    if: ${{ secrets.EXPO_TOKEN != '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Setup Expo CLI
        run: npm install -g @expo/cli eas-cli

      - name: Login to Expo
        run: |
          echo ${{ secrets.EXPO_TOKEN }} | eas login --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android APK
        run: |
          eas build --platform android --profile preview --non-interactive --output=./android-release.apk

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ./android-release.apk

  # iOS build
  build-ios:
    runs-on: macos-latest
    if: ${{ secrets.EXPO_TOKEN != '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Setup Expo CLI
        run: npm install -g @expo/cli eas-cli

      - name: Login to Expo
        run: |
          echo ${{ secrets.EXPO_TOKEN }} | eas login --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build iOS
        run: |
          eas build --platform ios --profile preview --non-interactive

  # Create release with mobile builds
  create-release:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    if: always() && (needs.build-android.result == 'success' || needs.build-ios.result == 'success')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: ./artifacts
        if: needs.build-android.result == 'success'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            ## ThePirithApp Release v${{ github.run_number }}

            ### What's New
            - Latest updates and bug fixes

            ### Downloads
            - **Android APK**: Direct installation for Android devices
            - **iOS IPA**: For iOS devices (requires sideloading)

            ### Installation Instructions
            - **Android**: Download APK and enable "Install from unknown sources"
            - **iOS**: Requires developer account or TestFlight

            Built automatically from commit: ${{ github.sha }}
          files: |
            ./artifacts/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Skip mobile builds if no token
  skip-mobile:
    runs-on: ubuntu-latest
    if: ${{ secrets.EXPO_TOKEN == '' }}
    steps:
      - name: Skip Mobile Build
        run: |
          echo "Skipping mobile build - EXPO_TOKEN not configured"
          echo "To enable mobile builds, add EXPO_TOKEN to repository secrets"
          echo "Get your token from: https://expo.dev/accounts/[username]/settings/access-tokens" 